---
title: "case_study"
author: "Ruilian Zhang"
date: "10/14/2021"
output: github_document
---

```{r}
library(tidyverse)
library(leaflet)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)
```


```{r}
library(p8105.datasets)

data(nyc_airbnb)
```


How many rentals are there? Of what type? In What places?

```{r}
nyc_airbnb = 
  nyc_airbnb %>% 
  mutate(stars = review_scores_location / 2) %>% 
  rename(borough = neighbourhood_group)
```

```{r}
nyc_airbnb %>% 
  janitor::tabyl(borough, room_type)

# the same table as above
nyc_airbnb %>% 
  count(borough, room_type) %>% 
  pivot_wider(
    names_from = room_type,
    values_from = n
  )
```


Look at price and room type

```{r}
nyc_airbnb %>% 
  ggplot(aes(x = stars, y = price)) +
  geom_point() + 
  facet_grid(. ~ room_type)
```

Price and neighbourhood

```{r}
nyc_airbnb %>% 
  filter(borough == "Manhattan") %>% 
  group_by(neighbourhood) %>% 
  summarize(mean_price = mean(price, na.rm = TRUE)) %>% 
  arrange(mean_price)

nyc_airbnb %>% 
  filter(borough == "Manhattan",
         price <= 1000) %>% 
  mutate(neighbourhood = 
           fct_reorder(neighbourhood, price)) %>% 
  ggplot(aes(x = neighbourhood, y = price)) +
  geom_boxplot() +
  coord_flip() +
  facet_grid(. ~ room_type)
```


Price vs location

```{r}
nyc_airbnb %>% 
  filter(price < 500) %>% 
  sample_n(5000) %>% # if the dataset is too big, make a sample
  ggplot(aes(x = lat, y = long, color = price)) +
  geom_point(alpha = .5 )
```


# retry leaflet

```{r, eval = FALSE}
nyc_airbnb %>% 
  leaflet()
```

